chore: update license + improve README
denosaurs/rutt pull request #3
Opened 2023-01-11 13:59 UTC by load1n9

2023-01-18 22:55 UTC, eliassjogreen requested changes

2023-01-18 22:55 UTC, eliassjogreen commented on LICENSE
> +Copyright (c) 2023 the denosaurs team
```suggestion
Copyright (c) 2022-2023 the denosaurs team
```

2023-01-18 22:55 UTC, eliassjogreen commented on README.md
> +Copyright 2023, the denosaurs team. All rights reserved. MIT license.
```suggestion
Copyright 2022-2023, the denosaurs team. All rights reserved. MIT license.
```

2023-01-18 22:55 UTC, eliassjogreen commented on examples/hello_world.ts
> -import { router } from "https://deno.land/x/rutt/mod.ts";
no, keep it this way, the import map fixes this for us that way the examples are kept the same as the actual code.

2023-01-18 22:55 UTC, eliassjogreen commented
Also fmt

2023-01-19 08:52 UTC, eliassjogreen commented on README.md
>  - Elias Sjögreen ([@eliassjogreen](https://github.com/eliassjogreen))
Want to be a maintainer?

2023-01-19 08:52 UTC, eliassjogreen approved these changes

2023-01-19 12:26 UTC, load1n9 commented on README.md
>  - Elias Sjögreen ([@eliassjogreen](https://github.com/eliassjogreen))
yes

2023-01-19 14:29 UTC, merged